Primeiro Envio do Projeto RF6 a 10
Team-Dire/airline-ticketing-system pull request #12
Opened 2022-12-16 16:45 UTC by GuiBatalhoti

Algumas alterações na Classe de "VooProgramado" e novas classes cridas.

2022-12-16 23:37 UTC, G-Nozawa requested changes
# Lista de defeitos:
## Diagrama de colaboração: Vender uma passagem.
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | - | IE | O sistema retorna uma lista de vagas disponíveis depois de inserir todas as informações da venda de passagem, contudo essa lista de assentos não é utilizada pelo controladorVenda, pois é o vooProgramado que verifica se é possível ocupar a vaga. |
| 2 | - | O | O método novoPassageiro recebe parâmetros nos quais não são passados para o seu método ativador ocuparVaga. |
| 3 | - | FI | Os métodos devem ser numerados informando os métodos que o chamaram (métodos ativadores). |

## Diagrama de classes:
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | - | I | O diagrama de comunicações sugere que existe uma relação direta entre vaga e vooProgramado, contudo o diagramas de classes apresenta uma classe "classes" na qual intermedia o vooProgramado e vaga. A classe "classes" deveria ser mencionada no diagrama de comunicação, ou uma nova relação entre vooProgramado e vaga deveria ser criada. |
| 2 | - | O | O diagrama de classes não apresenta a classe controladorVenda. |
| 3 | - | O | As classes do diagrama de classes não apresentam os novos métodos apresentados no diagrama de colaboração, e.g., método novaVenda da classe aeroporto. |

2022-12-18 20:49 UTC, GuiBatalhoti commented
Feita a primeira correção dos erros apontados pelo SQA. Por favor fazer uma nova revisão.

2022-12-18 22:40 UTC, G-Nozawa submitted a review, later dismissed
# Lista de defeitos:
## Diagrama de colaboração: Vender uma passagem.
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | - | IE | O método novaVenda não retorna um valor, contudo o método vagaLivreVooProgramado retorna um booleano. O método novaVenda não deveria retornar esse valor booleano para indicar o sucesso da operação de venda? |
| 2 | - | O | O método novoPassageiro não recebe o parâmetro tipoNumId, para identificar o tipo do documento do passageiro. |

## Diagrama de classes:
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | - | I | Os métodos novoPassageiro, da classe Vaga, novaVaga, da classe Classes, ocuparVagaClasse, da classe VooProgramado, e vagaLivreVooProgramado, da classe Aeroporto, não estão nas classes corretas segundo o diagrama de colaboração. Segundo o diagrama de colaboração, o método novoPassageiro deve pertencer a classe Passageiro, novaVaga não existe, ocuparVagaClasse pertence a Classes, e vagaLivreVooProgramado pertence a VooProgramado. |
| 2 | - | O | O método novoPassageiro não possui os parâmetros mencionados no diagrama de colaboração. |

2022-12-19 19:34 UTC, G-Nozawa commented
Ok

2022-12-19 19:57 UTC, merged